### ISSUE TITLE
Add Screenshots

### ISSUE THREAD

**Issue by achimmihca** [SDolha/ChartLibrary-Unity#1]
This lib sounds interesting. Could you add some screenshots please to see example results?

**Comment by sorin-ref** [comment]
I don't have Unity installed anymore to run the code, and I hope you forgive me that I won't; this was just an exercise. It looks like some (colorful) 3D bars, however:
https://en.wikipedia.org/wiki/Bar_chart#/media/File:Personal_pronouns2.jpg
